apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-aws
data:
  credentials:  |
    [default]
    aws_access_key_id=ASIA3LV35GSQB3QDNLXD
    aws_secret_access_key=qglotcoUjDqeKrWP9m3n9kiEfAX4dukwSA89RGG6
    aws_session_token=FwoGZXIvYXdzEEwaDCH7/gtl1vUBeg2ofyLVAaEX933Td6h5OFoLyolb+8jSxmRh4AGFX+alZp6ghX/z3h8qh/QMP/dOaYZa9q5u5OetQOG2P1e29pu9EgJVXyYou3syVbb5WetWyyr8z7HUFRZ8BiqkZIwU368fJ+cpqxVA8acAbMZAEQI8rKYcMWUJKP4zU6umBPgD4nRy1gRMAw/4S7D9Gv/Up04xDzhlRVUWIV+17g4mSFwyl2QthHokBiFGONT7sbKHIw7bkbc1tZJCtUFzOreGTbtLeQ4zDRgyysb4IeWxW6VSvH8oU/YLRRsqXCis3pWcBjItrDeWD9OS9nxPrr+jK56Vh9CWjvAgxhRf9FeACrS7YCEgvuD7n1qPYABlYh77