apiVersion: apps/v1

kind: Deployment

metadata:

  name: backend-feed

  labels:

    app: backend-feed

spec:

  replicas: 2

  selector:

    matchLabels:

      app: backend-feed

  template:

    metadata:

      labels:

        app: backend-feed

    spec:

      containers:
      - name: backend-feed
        image: trunghau4869/udagram-api-feed:v6
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef: 
              name: udagram-env
          - secretRef: 
              name: udagramdb-env      
