name: Udagram Cloud Developer - Monolith to Microservices Project
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Push Reverse Proxy Image to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t trunghau4869/reverseproxy:v3 ./udagram-reverseproxy
          docker push trunghau4869/reverseproxy:v3

  second_job:

    runs-on: ubuntu-latest



    steps:

      - uses: actions/checkout@v2

      - name: Build & Push Backend User Service Image to DockerHub

        run: |

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          docker build -t trunghau4869/udagram-api-user:v3 ./udagram-api-user

          docker push trunghau4869/udagram-api-user:v3

  third_job:

    runs-on: ubuntu-latest



    steps:

      - uses: actions/checkout@v2

      - name: Build & Push Backend Feed Service Image to DockerHub

        run: |

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          docker build -t trunghau4869/udagram-api-feed:v3 ./udagram-api-feed

          docker push trunghau4869/udagram-api-feed:v3

  forth_job:

    runs-on: ubuntu-latest



    steps:

      - uses: actions/checkout@v2

      - name: Build & Push Frontend Image to DockerHub

        run: |

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          docker build -t trunghau4869/udagram-frontend:v7 ./udagram-frontend

          docker push trunghau4869/udagram-frontend:v7