name: Udagram Cloud Developer - Monolith to Microservices Project
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run : docker-compose -f docker-compose-build.yaml build --parallel
      - run : docker tag udagram-frontend:local trunghau4869/udagram-frontend:v1
      - run : docker tag udagram-api-feed trunghau4869/udagram-api-feed:v1
      - run : docker tag udagram-api-user trunghau4869/udagram-api-user:v1
      - run : docker tag reverseproxy trunghau4869/reverseproxy:v1
      - run : echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME "--password-stdin   
      - run : docker push trunghau4869/udagram-api-feed:v1
      - run : docker push trunghau4869/udagram-api-user:v1
      - run : docker push trunghau4869/udagram-frontend:v1
      - run : docker push trunghau4869/reverseproxy:v1    
   