version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo apt install nodejs
            echo "--------- The images is Building ------------"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed coxmd/udagram-api-feed:v1
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user coxmd/udagram-api-user:v1
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend coxmd/udagram-frontend:v1
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy coxmd/udagram-reverseproxy:v1
            echo "-------- All images succesfully built----------"
            echo " ------- login in to hub--------"
            docker login -u coxmd -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push trunghau4869/reverseproxy:v4
            docker push trunghau4869/udagram-api-feed:v7
            docker push trunghau4869/udagram-api-user:v4
            docker push trunghau4869/udagram-frontend:v10
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
